import pandas as pd
from pathlib import Path
# let's create a set of locals referring to our directory and working directory 
home = Path.home()
work_dir = (home / 'proposing_truth')
data = (work_dir / 'data')
raw_data = (data / 'raw')
clean_data = (data / 'clean')
input = (work_dir / 'input')
output = (work_dir / 'output')
code = Path.cwd() 

# first hard-code senate co-sponsors
senate_cosponsors = pd.DataFrame([
    ['Matsunaga', 'Spark M.', 'D', 'HI'],
    ['Hayakawa', 'Samuel Ichiye', 'R', 'CA'],
    ['Cranston', 'Alan', 'D', 'CA'],
    ['McClure', 'James A.', 'R', 'ID'],
    ['Church', 'Frank', 'D', 'ID'],
    ['Melcher', 'John', 'D', 'MT'],
    ['Gravel', 'Mike', 'D', 'AK'],
    ['Goldwater', 'Barry', 'R', 'AZ'],
    ['Jackson', 'Henry M.', 'D', 'WA'],
    ['Armstrong', 'William L.', 'R', 'CO'],
    ['Magnuson', 'Warren G.', 'D', 'WA'],
    ['Leahy', 'Patrick J.', 'D', 'VT'],
    ['Bradley', 'Bill', 'D', 'NJ'],
    ['Boschwitz', 'Rudy', 'R', 'MN'],
    ['Durenberger', 'Dave', 'R', 'MN'],
    ['Mathias', 'Charles McC., Jr.', 'R', 'MD'],
    ['Levin', 'Carl', 'D', 'MI'],
    ['Hatch', 'Orrin G.', 'R', 'UT'],
    ['Percy', 'Charles H.', 'R', 'IL'],
    ['Stevens', 'Ted', 'R', 'AK'],
    ['Bayh', 'Birch', 'D', 'IN']
    ], columns=['last_name', 'first_name', 'party', 'state'])
# create variable 'cosponsor' == 1 for all senators in dataframe
senate_cosponsors['cosponsor'] = 1
senate_cosponsors.drop(columns={'first_name'}, inplace=True)
all_senators = pd.DataFrame([
    [1, 'Magnuson', 'Warren G.', 'D', 'WA'],
    [2, 'Young', 'Milton', 'R', 'ND'],
    [3, 'Stennis', 'John C.', 'D', 'MS'],
    [4, 'Long', 'Russell B.', 'D', 'LA'],
    [5, 'Jackson', 'Henry M.', 'D', 'WA'],
    [6, 'Thurmond', 'Strom', 'R', 'SC'],
    [7, 'Talmadge', 'Herman', 'D', 'GA'],
    [8, 'Church', 'Frank', 'D', 'ID'],
    [9, 'Javits', 'Jacob K.', 'R', 'NY'],
    [10, 'Proxmire', 'William', 'D', 'WI'],
    [11, 'Randolph', 'Jennings', 'D', 'WV'],
    [12, 'Byrd', 'Robert', 'D', 'WV'],
    [13, 'Williams', 'Harrison A.', 'D', 'NJ'],
    [14, 'Muskie', 'Edmund', 'D', 'ME'],
    [15, 'Cannon', 'Howard', 'D', 'NV'],
    [16, 'Burdick', 'Quentin N.', 'D', 'ND'],
    [17, 'Pell', 'Claiborne', 'D', 'RI'],
    [18, 'Tower', 'John', 'R', 'TX'],
    [19, 'Kennedy', 'Ted', 'D', 'MA'],
    [20, 'Ribicoff', 'Abraham A.', 'D', 'CT'],
    [21, 'McGovern', 'George', 'D', 'SD'],
    [22, 'Inouye', 'Daniel', 'D', 'HI'],
    [23, 'Bayh', 'Birch', 'D', 'IN'],
    [24, 'Nelson', 'Gaylord', 'D', 'WI'],
    [25, 'Byrd', 'Harry F., Jr.', 'I', 'VA'],
    [26, 'Hollings', 'Ernest', 'D', 'SC'],
    [27, 'Percy', 'Charles H.', 'R', 'IL'],
    [28, 'Baker', 'Howard', 'R', 'TN'],
    [29, 'Hatfield', 'Mark', 'R', 'OR'],
    [30, 'Stevens', 'Ted', 'R', 'AK'],
    [31, 'Eagleton', 'Thomas', 'D', 'MO'],
    [32, 'Goldwater', 'Barry', 'R', 'AZ'],
    [33, 'Schweiker', 'Richard', 'R', 'PA'],
    [34, 'Mathias', 'Charles', 'R', 'MD'],
    [35, 'Dole', 'Bob', 'R', 'KS'],
    [36, 'Bellmon', 'Henry', 'R', 'OK'],
    [37, 'Cranston', 'Alan', 'D', 'CA'],
    [38, 'Packwood', 'Bob', 'R', 'OR'],
    [39, 'Gravel', 'Mike', 'D', 'AK'],
    [40, 'Stevenson', 'Adlai III', 'D', 'IL'],
    [41, 'Roth', 'Bill', 'R', 'DE'],
    [42, 'Bentsen', 'Lloyd', 'D', 'TX'],
    [43, 'Weicker', 'Lowell', 'R', 'CT'],
    [44, 'Chiles', 'Lawton', 'D', 'FL'],
    [45, 'Stafford', 'Robert', 'R', 'VT'],
    [46, 'Nunn', 'Sam', 'D', 'GA'],
    [47, 'Johnston', 'Bennett, Jr.', 'D', 'LA'],
    [48, 'McClure', 'James A.', 'R', 'ID'],
    [49, 'Helms', 'Jesse', 'R', 'NC'],
    [50, 'Huddleston', 'Walter', 'D', 'KY'],
    [51, 'Domenici', 'Pete', 'R', 'NM'],
    [52, 'Biden', 'Joe', 'D', 'DE'],
    [53, 'Laxalt', 'Paul', 'R', 'NV'],
    [54, 'Garn', 'Jake', 'R', 'UT'],
    [55, 'Glenn', 'John', 'D', 'OH'],
    [56, 'Ford', 'Wendell H.', 'D', 'KY'],
    [57, 'Stone', 'Richard', 'D', 'FL'],
    [58, 'Culver', 'John', 'D', 'IA'],
    [59, 'Bumpers', 'Dale', 'D', 'AR'],
    [60, 'Morgan', 'Robert B.', 'D', 'NC'],
    [61, 'Hart', 'Gary', 'D', 'CO'],
    [62, 'Leahy', 'Patrick', 'D', 'VT'],
    [63, 'Durkin', 'John', 'D', 'NH'],
    [64, 'Danforth', 'John', 'R', 'MO'],
    [65, 'Zorinsky', 'Edward', 'D', 'NE'],
    [66, 'Metzenbaum', 'Howard', 'D', 'OH'],
    [67, 'Chafee', 'John', 'R', 'RI'],
    [68, 'Riegle', 'Donald W., Jr.', 'D', 'MI'],
    [69, 'Hayakawa', 'Samuel', 'R', 'CA'],
    [70, 'Matsunaga', 'Spark', 'D', 'HI'],
    [71, 'Melcher', 'John', 'D', 'MT'],
    [72, 'Heinz', 'H. John III', 'R', 'PA'],
    [73, 'Sarbanes', 'Paul', 'D', 'MD'],
    [74, 'Moynihan', 'Pat', 'D', 'NY'],
    [75, 'Lugar', 'Richard', 'R', 'IN'],
    [76, 'Sasser', 'Jim', 'D', 'TN'],
    [77, 'DeConcini', 'Dennis', 'D', 'AZ'],
    [78, 'Hatch', 'Orrin', 'R', 'UT'],
    [79, 'Schmitt', 'Harrison', 'R', 'NM'],
    [80, 'Wallop', 'Malcolm', 'R', 'WY'],
    [81, 'Durenberger', 'David', 'R', 'MN'],
    [82, 'Stewart', 'Donald W.', 'D', 'AL'],
    [83, 'Baucus', 'Max', 'D', 'MT'],
    [84, 'Kassebaum Baker', 'Nancy', 'R', 'KS'],
    [85, 'Cochran', 'Thad', 'R', 'MS'],
    [86, 'Boschwitz', 'Rudy', 'R', 'MN'],
    [87, 'Simpson', 'Alan K.', 'R', 'WY'],
    [88, 'Warner', 'John', 'R', 'VA'],
    [89, 'Pryor', 'David', 'D', 'AR'],
    [90, 'Cohen', 'William', 'R', 'ME'],
    [91, 'Tsongas', 'Paul', 'D', 'MA'],
    [92, 'Armstrong', 'William L.', 'R', 'CO'],
    [93, 'Pressler', 'Larry', 'R', 'SD'],
    [94, 'Boren', 'David L.', 'D', 'OK'],
    [95, 'Exon', 'J. James', 'D', 'NE'],
    [96, 'Levin', 'Carl', 'D', 'MI'],
    [97, 'Bradley', 'Bill', 'D', 'NJ'],
    [98, 'Heflin', 'Howell', 'D', 'AL'],
    [99, 'Jepsen', 'Roger', 'R', 'IA'],
    [100, 'Humphrey', 'Gordon J.', 'R', 'NH'],
    ], columns = ['seniority', 'last_name', 'first_name', 'party', 'state'])
# merge 
all_senators = all_senators.merge(senate_cosponsors, on=['last_name', 'party', 'state'], how='outer', indicator=True)
all_senators.drop(columns={'_merge'}, inplace=True)
# fill NaN values with 0
all_senators['cosponsor'] = all_senators['cosponsor'].fillna(0)
all_senators.to_csv(clean_data / 'all_senators.csv', index=False)

representative_cosponsors = pd.DataFrame([
    ['Rodino', 'Peter W., Jr.', 'D', 'NJ-10'],
    ['Mineta', 'Norman Y.', 'D', 'CA-13'],
    ['Matsui', 'Robert T.', 'D', 'CA-5'],
    ['Brademas', 'John', 'D', 'IN-3'],
    ['Burton', 'Phillip', 'D', 'CA-6'],
    ['Yates', 'Sidney R.', 'D', 'IL-9'],
    ['Anderson', 'Glenn M.', 'D', 'CA-32'],
    ['Simon', 'Paul', 'D', 'IL-24'],
    ['Akaka', 'Daniel K.', 'D', 'HI-2'],
    ['Badham', 'Robert E.', 'R', 'CA-40'],
    ['Barnes', 'Michael D.', 'D', 'MD-8'],
    ['Bedell', 'Berkley W.', 'D', 'IA-6'],
    ['Beilenson', 'Anthony C.', 'D', 'CA-23'],
    ['Blanchard', 'James', 'D', 'MI-18'],
    ['Bonior', 'David E.', 'D', 'MI-12'],
    ['Bonker', 'Don', 'D', 'WA-3'],
    ['Brown', 'George E., Jr.', 'D', 'CA-36'],
    ['Burgener', 'Clair W.', 'R', 'CA-43'],
    ['Burlison', 'Bill D.', 'D', 'MO-10'],
    ['Burton', 'John', 'D', 'CA-5'],
    ['Butler', 'M. Caldwell', 'R', 'VA-6'],
    ['Chisholm', 'Shirley', 'D', 'NY-12'],
    ['Clausen', 'Don H.', 'R', 'CA-2'],
    ['Clay', 'William (Bill)', 'D', 'MO-1'],
    ['Coelho', 'Anthony Lee', 'D', 'CA-15'],
    ['Corman', 'James C.', 'D', 'CA-21'],
    ['Danielson', 'George E.', 'D', 'CA-30'],
    ['Dannemeyer', 'William E.', 'R', 'CA-39'],
    ['Dellums', 'Ronald V.', 'D', 'CA-8'],
    ['Dicks', 'Norman D.', 'D', 'WA-6'],
    ['Dingell', 'John D.', 'D', 'MI-16'],
    ['Dixon', 'Julian C.', 'R', 'CA-32'],
    ['Dornan', 'Robert K.', 'R', 'CA-27'],
    ['Duncan', 'Robert B.', 'D', 'OR-3'],
    ['Edgar', 'Robert W.', 'D', 'PA-7'],
    ['Edwards', 'Don', 'D', 'CA-10'],
    ['Evans', 'David W.', 'D', 'IN-6'],
    ['Fary', 'John G.', 'D', 'IL-5'],
    ['Fascell', 'Dante B.', 'D', 'FL-15'],
    ['Fazio', 'Vic', 'D', 'CA-3'],
    ['Fenwick', 'Millicent H.', 'R', 'NJ-5'],
    ['Fish', 'Hamilton, Jr.', 'R', 'NY-25'],
    ['Florio', 'James J.', 'D', 'NJ-1'],
    ['Foley', 'Thomas S.', 'D', 'WA-5'],
    ['Ford', 'William D.', 'D', 'MI-15'],
    ['Forsythe', 'Edwin B.', 'R', 'NJ-6'],
    ['Frost', 'Martin', 'D', 'TX-24'],
    ['Gephardt', 'Richard A.', 'D', 'MO-3'],
    ['Gilman', 'Benjamin A.', 'R', 'NY-26'],
    ['Gray', 'William H., III', 'D', 'PA-2'],
    ['Green', 'S. William', 'R', 'NY-18'],
    ['Hansen', 'George V.', 'R', 'ID-2'],
    ['Hawkins', 'Augustus F.', 'D', 'CA-29'],
    ['Heftel', 'Cecil', 'D', 'HI-1'],
    ['Harkin', 'Tom', 'D', 'IA-5'],
    ['Howard', 'James J.', 'D', 'NJ-3'],
    ['Hughes', 'William J.', 'D', 'NJ-2'],
    ['Jacobs', 'Andrew, Jr.', 'D', 'IN-11'],
    ['Johnson', 'Harold T.', 'D', 'CA-1'],
    ['Kastenmeier', 'Robert W.', 'D', 'WI-2'],
    ['Kildee', 'Dale E.', 'D', 'MI-7'],
    ['Kogovsek', 'Ray', 'D', 'CO-3'],
    ['Kostmayer', 'Peter H.', 'D', 'PA-8'],
    ['Lagomarsino', 'Robert J.', 'R', 'CA-19'],
    ['Leath', 'Marvin', 'D', 'TX-11'],
    ['Lehman', 'William', 'D', 'FL-13'],
    ['Leland', 'Mickey', 'D', 'TX-18'],
    ['Lewis', 'Jerry', 'R', 'CA-41'],
    ['Lloyd', 'James F.', 'D', 'CA-35'],
    ['Lowry', 'Mike', 'D', 'WA-7'],
    ['Lungren', 'Daniel E.', 'R', 'CA-3'],
    ['Mavroules', 'Nicholas', 'D', 'MA-6'],
    ['McCloskey', 'Paul N., Jr.', 'R', 'CA-12'],
    ['McKay', 'K. Gunn', 'D', 'UT-1'],
    ['Mikulski', 'Barbara A.', 'D', 'MD-3'],
    ['Miller', 'George', 'D', 'CA-7'],
    ['Mitchell', 'Parren J.', 'D', 'MD-7'],
    ['Moorhead', 'Carlos J.', 'R', 'CA-22'],
    ['Murphy', 'Morgan F.', 'D', 'IL-2'],
    ['Oberstar', 'James L.', 'D', 'MN-8'],
    ['Panetta', 'Leon', 'D', 'CA-16'],
    ['Pashayan', 'Charles, Jr.', 'R', 'CA-17'],
    ['Patten', 'Edward J.', 'D', 'NJ-15'],
    ['Patterson', 'Jerry M.', 'D', 'CA-38']
], columns = ['last_name', 'first_name', 'party', 'state_district'])
representative_cosponsors['cosponsor'] = 1

